image: golang:1.8

test:
  only:
    - master
    - tags
  script:
    - apt-get update -y
    - apt-get install ruby -y
    - gem install dpl
    - go get github.com/constabulary/gb/...
    - go get -u github.com/golang/lint/golint
    - make
    - dpl --provider=heroku --app=msu-go-2017 --api-key=$HEROKU_PRODUCTION_API_KEY --skip_cleanup